### ISSUE TITLE
About the Multiface dataset

### ISSUE THREAD

**Issue by KVBK01** [uuembodiedsocialai/FaceDiffuser#9]
Thanks for the great work and code!
I have one question prior to downloading the Multiface dataset.
Does the training involves using the whole Multiface dataset (which is quite large), or just downloading the mini version suffices?

**Comment by ChenVoid** [comment]
Maybe the large one. Cause the mini dataset is too small. But I can't parse it by the script after downloading the data.

**Comment by galib360** [comment]
Thank you for the question. In our work, we used the publicly released version (https://github.com/facebookresearch/multiface/tree/main). The original dataset consists of 250 subjects whereas the publicly released version has 13 subjects. In our work, we used 13 subjects, each uttering 50 sentences. However, due to missing data (at the time of our work), there are two subjects that do not have scanned data for all 50 uttered sentences. (https://arxiv.org/pdf/2309.11306.pdf) page 13 of our paper shows how we used the dataset.
